#
# Authors:     PN
# Maintainers: PN
# Copyright:   2024, UWCHR, GPL v2 or later
# ============================================
# describe-sea/docs/Makefile

.PHONY: all

all: \
		../write/output/border-everywhere.html
	cp -r ../write/output/*.html .

# done.
